apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-cache
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /home/githop/.cache/huggingface
