apiVersion: v1
kind: PersistentVolume
metadata:
  name: proxy-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /var/lib/gnarlyvllm/proxy-logs
