apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-logs
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: proxy-logs
